---
- hosts: master
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Login Dockerhub
      shell: docker login -u "{{DOCKER_HUB_USERNAME}}" -p "{{DOCKER_HUB_PASSWORD}}"
    
    - name: Copy file
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/
    
    - name: Restart docker-compose
      shell: |
          docker-compose stop
          docker-compose rm -f
          docker-compose pull
          docker-compose up -d